"use client";

import { FormEvent, useEffect, useState } from "react";
/* Media URLs may come from configured external storage providers. */
/* eslint-disable @next/next/no-img-element */
type Asset = { id: string; url: string; alt: string | null; filename: string | null };
export default function AdminMediaPage() { const [assets, setAssets] = useState<Asset[]>([]); const [url, setUrl] = useState(""); const [message, setMessage] = useState(""); async function load() { const response = await fetch("/api/admin/media"); if (response.ok) setAssets(await response.json()); } // Hydrate the media grid from the authenticated API.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, []); async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/media", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url }) }); setMessage(response.ok ? "Image saved." : "Enter a valid image URL."); if (response.ok) { setUrl(""); load(); } } async function remove(id: string) { if (window.confirm("Delete this media asset?")) { await fetch(`/api/admin/media/${id}`, { method: "DELETE" }); load(); } } return <div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#71808c]">Assets</p><h1 className="mt-2 text-3xl font-semibold">Media Library</h1><form onSubmit={submit} className="mt-8 flex max-w-2xl gap-3"><input required type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="Paste image URL" className="admin-input" /><button className="shrink-0 rounded-md bg-[#2563eb] px-4 py-2.5 text-sm font-medium text-white">Add image</button></form>{message && <p className="mt-3 text-sm text-[#287a3d]">{message}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{assets.map((asset) => <div key={asset.id} className="overflow-hidden rounded-lg border border-[#e2e7eb] bg-white"><div className="relative aspect-square bg-[#f1f3f5]"><img src={asset.url} alt={asset.alt ?? ""} className="h-full w-full object-cover" /></div><div className="flex justify-between gap-2 p-3"><button onClick={() => navigator.clipboard.writeText(asset.url)} className="text-sm text-[#2563eb]">Copy URL</button><button onClick={() => remove(asset.id)} className="text-sm text-[#b42318]">Delete</button></div></div>)}{!assets.length && <div className="rounded-lg border border-dashed border-[#cbd5dc] p-8 text-sm text-[#71808c]">No media assets saved.</div>}</div></div>; }
