"use client";

import { FormEvent, useEffect, useState } from "react";

const defaults = { brandName: "SHARKI", brandSubtitle: "NIGHTWEARS", description: "Nightwear made with the patience of a manufacturer and the eye of a modern Indian label.", newsletterText: "New drops, thoughtful stories and a softer way to start the day.", copyright: "© 2025 SHARKI NIGHTWEARS" };
export default function AdminFooterPage() { const [form, setForm] = useState(defaults); const [message, setMessage] = useState(""); // Hydrate from shared persisted footer content.
  useEffect(() => { fetch("/api/admin/content/footer").then((response) => response.json()).then((data) => setForm({ ...defaults, ...data })); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/content/footer", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); setMessage(response.ok ? "Footer settings saved." : "Unable to save footer settings."); }
  return <div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#71808c]">Website content</p><h1 className="mt-2 text-3xl font-semibold">Footer</h1><form onSubmit={submit} className="mt-8 max-w-3xl space-y-5 rounded-lg border border-[#e2e7eb] bg-white p-6"><input value={form.brandName} onChange={(event) => setForm({ ...form, brandName: event.target.value })} placeholder="Brand name" className="admin-input" /><input value={form.brandSubtitle} onChange={(event) => setForm({ ...form, brandSubtitle: event.target.value })} placeholder="Brand subtitle" className="admin-input" /><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Brand description" className="admin-input" /><textarea value={form.newsletterText} onChange={(event) => setForm({ ...form, newsletterText: event.target.value })} placeholder="Newsletter text" className="admin-input" /><input value={form.copyright} onChange={(event) => setForm({ ...form, copyright: event.target.value })} placeholder="Copyright text" className="admin-input" /><button className="rounded-md bg-[#2563eb] px-4 py-2.5 text-sm font-medium text-white">Save footer</button>{message && <p className="text-sm text-[#287a3d]">{message}</p>}</form></div>; }
