"use client";

import { FormEvent, useEffect, useState } from "react";
import { defaultHomepageContent } from "@/lib/site-content";

export default function AdminHomepagePage() {
  const [images, setImages] = useState(defaultHomepageContent.heroImages.join("\n"));
  const [interval, setIntervalValue] = useState(String(defaultHomepageContent.heroInterval));
  const [heading, setHeading] = useState(""); const [description, setDescription] = useState(""); const [buttonText, setButtonText] = useState(""); const [buttonLink, setButtonLink] = useState(""); const [active, setActive] = useState(true);
  const [message, setMessage] = useState("");
  // Hydrate the editor from the shared content record.
  useEffect(() => { fetch("/api/admin/content/homepage").then((response) => response.json()).then((data) => { if (Array.isArray(data.heroImages)) setImages(data.heroImages.join("\n")); if (data.heroInterval) setIntervalValue(String(data.heroInterval)); setHeading(data.heading ?? ""); setDescription(data.description ?? ""); setButtonText(data.buttonText ?? ""); setButtonLink(data.buttonLink ?? ""); setActive(data.active !== false); }); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/content/homepage", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ heroImages: images.split("\n").map((image) => image.trim()).filter(Boolean), heroInterval: Number(interval) || 1000, heading, description, buttonText, buttonLink, active }) }); setMessage(response.ok ? "Homepage settings saved." : "Unable to save homepage settings."); }
  return <div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#71808c]">Website content</p><h1 className="mt-2 text-3xl font-semibold">Hero</h1><p className="mt-2 text-sm text-[#71808c]">These values are stored in the shared database and used by the public homepage hero.</p><form onSubmit={submit} className="mt-8 max-w-3xl space-y-5 rounded-lg border border-[#e2e7eb] bg-white p-6"><input value={heading} onChange={(event) => setHeading(event.target.value)} placeholder="Hero heading" className="admin-input" /><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Hero description" className="admin-input" /><div className="grid gap-4 md:grid-cols-2"><input value={buttonText} onChange={(event) => setButtonText(event.target.value)} placeholder="Button text" className="admin-input" /><input value={buttonLink} onChange={(event) => setButtonLink(event.target.value)} placeholder="Button link" className="admin-input" /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} /> Hero active</label><div><label className="mb-2 block text-sm font-medium">Hero image URLs</label><textarea value={images} onChange={(event) => setImages(event.target.value)} rows={6} className="admin-input" /></div><div><label className="mb-2 block text-sm font-medium">Slider interval (milliseconds)</label><input required type="number" min="250" value={interval} onChange={(event) => setIntervalValue(event.target.value)} className="admin-input max-w-xs" /></div><button className="rounded-md bg-[#2563eb] px-4 py-2.5 text-sm font-medium text-white">Save hero settings</button>{message && <p className="text-sm text-[#287a3d]">{message}</p>}</form></div>;
}
